### ISSUE TITLE
EO snippets in YAML packs are not checked for errors

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/lints#530]
In YAML tests packs, we have EO snippets (`input` key in the single pack, and `*.eo` in the WPA pack). During the test run, we parse those snippets into XMIRs, in order to pass them as inputs to lints, and then we make an assertions about the lint result. Take a look at this example:

```yaml
sheets:
  - /org/eolang/lints/names/anonymous-formation.xsl
asserts:
  - /defects[count(defect[@severity='warning'])=0]
input: |
  # Main.
  malloc.of
    64
    [m] >>
      QQ.io.stdout > @
        "foo"
```
 
Let's say EO snippet (`input`) cannot be parsed (contains errors), however, test pack will pass. To make our test pipeline more robust, I suggest to check that each EO snippet does not contain any errors (in both scopes: single and WPA).
